version: '3.8'

services: 
  server: 
    container_name: server_node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 4040:4040
    networks:
      - dapp-network
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shopping
    networks:
      - dapp-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: shopping
      ME_CONFIG_MONGODB_URL: mongodb://root:shopping@mongo:27017/
    networks:
      - dapp-network
  minio:
    image: minio/minio:latest
    container_name: experiments_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=password
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - dapp-network
networks:
  dapp-network:
    driver: bridge
