version: '3.8'

services: 
  server: 
    container_name: server_node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 5500:5500
    networks:
      - dapp-network
    depends_on:
      - db
      
  db: 
    container_name: db_mongoose
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - .:/app
    ports:
      - 27012:27017
    networks:
      - dapp-network
    

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports: 
      - 8085:8085
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://root:12345@mongo:27017/
    networks:
      - dapp-network

networks:
  dapp-network:
    driver: bridge
